<template>
  <Layout>
    <h1>Power Generator</h1>
    <div>
      <p>Generate a random power for your character.</p>
      <button class="bg-green-600 hover:bg-green-700 px-3 py-2 rounded text-white" @click="generatePower">Generate
        Power
      </button>

      <div class="flex flex-col gap-3">
        <span class="font-bold">Power Name:</span> {{ randomized.power }}
        <span class="font-bold">Scope:</span> {{ randomized.scope }}
        <span class="font-bold">Range:</span> {{ randomized.range }}
        <span class="font-bold">Area of Effect:</span> {{ randomized.areaOfEffect }}
        <span class="font-bold">Power Level:</span> {{ randomized.powerLevel }}

      </div>
    </div>
  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: 'Power Generator'
  },
  methods: {
    generatePower() {
      let power = this.getRandomElement(this.dataSet.powers)
      this.randomized.power = power.name;
      this.randomized.powerUrl = power.url;
      this.randomized.scope = this.getRandomElement(this.dataSet.scopes);
      this.randomized.range = this.getRandomElement(this.dataSet.ranges);
      this.randomized.areaOfEffect = this.getRandomElement(this.dataSet.areasOfEffect);
      this.randomized.powerLevel = this.getRandomElement(this.dataSet.powerLevels);
      // this.randomized.powerUrl
    },
    getRandomElement(array) {
      return array[Math.floor(Math.random()*array.length)];
    }
  },
  data() {
    return {
      randomized: {
        power: '',
        powerUrl: '',
        scope: '',
        range: '',
        powerLevel: '',
        areaOfEffect: '',
      },
      dataSet: {
        scopes: [
          'self',
          'others',
          'objects',
        ],
        powerLevels: {
          1: 'minor',
          2: 'moderate',
          3: 'major',
        },
        ranges: [
          'contact',
          'line of sight',
          '10 ft',
          '30 ft',
          '100 ft',
        ],
        areasOfEffect: [
          'pinpoint',
          '5-20 ft radius',
        ],
        powers: [
          {"url": "https://www.superherodb.com/ability-shift/60-63/*", "name": "Ability Shift"},
          {"url": "https://www.superherodb.com/abstract-existence/60-530/*/", "name": "Abstract Existence"},
          {"url": "https://www.superherodb.com/acausality/60-201/*/", "name": "Acausality"},
          {"url": "https://www.superherodb.com/accelerated-development/60-306/*/", "name": "Accelerated Development"},
          {"url": "https://www.superherodb.com/accelerated-healing/60-74/*/", "name": "Accelerated Healing"},
          {"url": "https://www.superherodb.com/acid-manipulation/60-361/*/", "name": "Acid Manipulation"},
          {"url": "https://www.superherodb.com/acid-resistants/60-513/*/", "name": "Acid Resistants"},
          {"url": "https://www.superherodb.com/acidic-spit/60-389/*/", "name": "Acidic Spit"},
          {"url": "https://www.superherodb.com/acrobatics/60-315/*/", "name": "Acrobatics"},
          {"url": "https://www.superherodb.com/adaptation/60-65/*/", "name": "Adaptation"},
          {"url": "https://www.superherodb.com/age-manipulation/60-202/*/", "name": "Age Manipulation"},
          {"url": "https://www.superherodb.com/agility/60-107/*/", "name": "Agility"},
          {"url": "https://www.superherodb.com/amphibious-respiration/60-377/*/", "name": "Amphibious Respiration"},
          {"url": "https://www.superherodb.com/animal-attributes/60-1/*/", "name": "Animal Attributes"},
          {"url": "https://www.superherodb.com/animal-control/60-182/*/", "name": "Animal Control"},
          {"url": "https://www.superherodb.com/animal-oriented-powers/60-2/*/", "name": "Animal Oriented Powers"},
          {"url": "https://www.superherodb.com/animation/60-36/*/", "name": "Animation"},
          {"url": "https://www.superherodb.com/anti-gravity/60-149/*/", "name": "Anti-Gravity"},
          {"url": "https://www.superherodb.com/antiforce-manipulation/60-501/*/", "name": "Antiforce Manipulation"},
          {"url": "https://www.superherodb.com/antimatter-manipulation/60-285/*/", "name": "Antimatter Manipulation"},
          {"url": "https://www.superherodb.com/apathy/60-266/*/", "name": "Apathy"},
          {"url": "https://www.superherodb.com/apotheosis/60-66/*/", "name": "Apotheosis"},
          {"url": "https://www.superherodb.com/arcane-magic/60-384/*/", "name": "Arcane Magic"},
          {"url": "https://www.superherodb.com/astral-projection/60-37/*/", "name": "Astral Projection"},
          {"url": "https://www.superherodb.com/astral-trap/60-38/*/", "name": "Astral Trap"},
          {"url": "https://www.superherodb.com/astro-force/60-193/*/", "name": "Astro Force"},
          {"url": "https://www.superherodb.com/attack-negation/60-400/*/", "name": "Attack Negation"},
          {"url": "https://www.superherodb.com/attack-reflection/60-299/*/", "name": "Attack Reflection"},
          {"url": "https://www.superherodb.com/audio-alteration/60-404/*/", "name": "Audio Alteration"},
          {"url": "https://www.superherodb.com/audio-control/60-10/*/", "name": "Audio Control"},
          {"url": "https://www.superherodb.com/aura/60-270/*/", "name": "Aura"},
          {"url": "https://www.superherodb.com/avatar-creation/60-341/*/", "name": "Avatar Creation"},
          {"url": "https://www.superherodb.com/awakened-power/60-305/*/", "name": "Awakened Power"},
          {"url": "https://www.superherodb.com/axis-manipulation/60-531/*/", "name": "Axis Manipulation"},
          {"url": "https://www.superherodb.com/banish/60-39/*/", "name": "Banish"},
          {"url": "https://www.superherodb.com/berserk-mode/60-228/*/", "name": "Berserk Mode"},
          {"url": "https://www.superherodb.com/biokinesis/60-11/*/", "name": "Biokinesis"},
          {"url": "https://www.superherodb.com/bionics/60-390/*/", "name": "Bionics"},
          {"url": "https://www.superherodb.com/black-hole-manipulation/60-345/*/", "name": "Black Hole Manipulation"},
          {"url": "https://www.superherodb.com/blessed/60-317/*/", "name": "Blessed"},
          {"url": "https://www.superherodb.com/blood-manipulation/60-332/*/", "name": "Blood Manipulation"},
          {"url": "https://www.superherodb.com/bloodlust/60-267/*/", "name": "Bloodlust"},
          {"url": "https://www.superherodb.com/body-inflation/60-526/*/", "name": "Body Inflation"},
          {"url": "https://www.superherodb.com/body-puppetry/60-325/*/", "name": "Body Puppetry"},
          {"url": "https://www.superherodb.com/bone-manipulation/60-326/*/", "name": "Bone Manipulation"},
          {"url": "https://www.superherodb.com/broadway-force/60-401/*/", "name": "Broadway Force"},
          {"url": "https://www.superherodb.com/bullet-time/60-67/*/", "name": "Bullet Time"},
          {"url": "https://www.superherodb.com/camouflage/60-120/*/", "name": "Camouflage"},
          {"url": "https://www.superherodb.com/causality-manipulation/60-216/*/", "name": "Causality Manipulation"},
          {"url": "https://www.superherodb.com/causality-resistance/60-491/*/", "name": "Causality Resistance"},
          {"url": "https://www.superherodb.com/chain-manipulation/60-293/*/", "name": "Chain Manipulation"},
          {"url": "https://www.superherodb.com/changing-armor/60-68/*/", "name": "Changing Armor"},
          {"url": "https://www.superherodb.com/chaos-energy/60-477/*/", "name": "Chaos Energy"},
          {"url": "https://www.superherodb.com/chaos-magic/60-203/*/", "name": "Chaos Magic"},
          {"url": "https://www.superherodb.com/chaos-manipulation/60-333/*/", "name": "Chaos Manipulation"},
          {"url": "https://www.superherodb.com/chemokinesis/60-360/*/", "name": "Chemokinesis"},
          {"url": "https://www.superherodb.com/chi-manipulation/60-204/*/", "name": "Chi Manipulation"},
          {"url": "https://www.superherodb.com/clairvoyance-resistance/60-416/*/", "name": "Clairvoyance Resistance"},
          {"url": "https://www.superherodb.com/clairvoyance/60-40/*/", "name": "Clairvoyance"},
          {"url": "https://www.superherodb.com/cloaking/60-181/*/", "name": "Cloaking"},
          {"url": "https://www.superherodb.com/cloning/60-385/*/", "name": "Cloning"},
          {"url": "https://www.superherodb.com/cloth-manipulation/60-388/*/", "name": "Cloth Manipulation"},
          {"url": "https://www.superherodb.com/cobra-kai-karate/60-419/*/", "name": "Cobra Kai Karate"},
          {"url": "https://www.superherodb.com/cold-resistance/60-152/*/", "name": "Cold Resistance"},
          {"url": "https://www.superherodb.com/compassion-inducement/60-311/*/", "name": "Compassion Inducement"},
          {"url": "https://www.superherodb.com/conceptual-manipulation/60-217/*/", "name": "Conceptual Manipulation"},
          {"url": "https://www.superherodb.com/corruption-resistance/60-372/*/", "name": "Corruption Resistance"},
          {"url": "https://www.superherodb.com/corruption/60-300/*/", "name": "Corruption"},
          {"url": "https://www.superherodb.com/cosmic-awareness/60-394/*/", "name": "Cosmic Awareness"},
          {"url": "https://www.superherodb.com/creation/60-232/*/", "name": "Creation"},
          {"url": "https://www.superherodb.com/cryokinesis/60-14/*/", "name": "Cryokinesis"},
          {"url": "https://www.superherodb.com/curse-manipulation/60-335/*/", "name": "Curse Manipulation"},
          {"url": "https://www.superherodb.com/curse-resistance/60-490/*/", "name": "Curse Resistance"},
          {"url": "https://www.superherodb.com/damage-boost/60-303/*/", "name": "Damage Boost"},
          {"url": "https://www.superherodb.com/damage-reduction/60-318/*/", "name": "Damage Reduction"},
          {"url": "https://www.superherodb.com/damage-transferal/60-319/*/", "name": "Damage Transferal"},
          {"url": "https://www.superherodb.com/danger-sense/60-42/*/", "name": "Danger Sense"},
          {"url": "https://www.superherodb.com/danmaku/60-242/*/", "name": "Danmaku"},
          {"url": "https://www.superherodb.com/dark-arts/60-331/*/", "name": "Dark Arts"},
          {"url": "https://www.superherodb.com/dark-magic/60-428/*/", "name": "Dark Magic"},
          {
            "url": "https://www.superherodb.com/dark-matter-manipulation/60-517/*/",
            "name": "Dark Matter Manipulation",
          },
          {"url": "https://www.superherodb.com/darkforce-manipulation/60-150/*/", "name": "Darkforce Manipulation"},
          {"url": "https://www.superherodb.com/data-manipulation/60-362/*/", "name": "Data Manipulation"},
          {"url": "https://www.superherodb.com/death-manipulation/60-218/*/", "name": "Death Manipulation"},
          {"url": "https://www.superherodb.com/death-touch/60-172/*/", "name": "Death Touch"},
          {"url": "https://www.superherodb.com/decay-embodiment/60-327/*/", "name": "Decay Embodiment"},
          {"url": "https://www.superherodb.com/density-control/60-69/*/", "name": "Density Control"},
          {"url": "https://www.superherodb.com/dexterity/60-109/*/", "name": "Dexterity"},
          {"url": "https://www.superherodb.com/dimension-storage/60-277/*/", "name": "Dimension Storage"},
          {"url": "https://www.superherodb.com/dimensional-awareness/60-41/*/", "name": "Dimensional Awareness"},
          {"url": "https://www.superherodb.com/dimensional-travel/60-157/*/", "name": "Dimensional Travel"},
          {"url": "https://www.superherodb.com/disguise-mastery/60-380/*/", "name": "Disguise Mastery"},
          {"url": "https://www.superherodb.com/divinity/60-393/*/", "name": "Divinity"},
          {"url": "https://www.superherodb.com/dream-manipulation/60-205/*/", "name": "Dream Manipulation"},
          {"url": "https://www.superherodb.com/duplication/60-70/*/", "name": "Duplication"},
          {"url": "https://www.superherodb.com/durability-negation/60-243/*/", "name": "Durability Negation"},
          {"url": "https://www.superherodb.com/durability/60-111/*/", "name": "Durability"},
          {"url": "https://www.superherodb.com/eagle-fang-karate/60-420/*/", "name": "Eagle Fang Karate"},
          {"url": "https://www.superherodb.com/ectoplasm-manipulation/60-344/*/", "name": "Ectoplasm Manipulation"},
          {"url": "https://www.superherodb.com/elasticity/60-71/*/", "name": "Elasticity"},
          {"url": "https://www.superherodb.com/electrical-transport/60-87/*/", "name": "Electrical Transport"},
          {"url": "https://www.superherodb.com/electricity-absorption/60-355/*/", "name": "Electricity Absorption"},
          {"url": "https://www.superherodb.com/electricity-resistance/60-356/*/", "name": "Electricity Resistance"},
          {
            "url": "https://www.superherodb.com/electro-magnetism-manipulation/60-403/*/",
            "name": "Electro-Magnetism Manipulation",
          },
          {"url": "https://www.superherodb.com/electrokinesis/60-16/*/", "name": "Electrokinesis"},
          {"url": "https://www.superherodb.com/elemental-transformation/60-3/*/", "name": "Elemental Transformation"},
          {"url": "https://www.superherodb.com/emotional-power-up/60-244/*/", "name": "Emotional Power Up"},
          {"url": "https://www.superherodb.com/emp-generation/60-418/*/", "name": "EMP Generation"},
          {"url": "https://www.superherodb.com/empathy/60-57/*/", "name": "Empathy"},
          {"url": "https://www.superherodb.com/endurance/60-112/*/", "name": "Endurance"},
          {"url": "https://www.superherodb.com/energy-absorption/60-110/*/", "name": "Energy Absorption"},
          {"url": "https://www.superherodb.com/energy-armor/60-28/*/", "name": "Energy Armor"},
          {"url": "https://www.superherodb.com/energy-beams/60-29/*/", "name": "Energy Beams"},
          {"url": "https://www.superherodb.com/energy-blasts/60-30/*/", "name": "Energy Blasts"},
          {"url": "https://www.superherodb.com/energy-constructs/60-161/*/", "name": "Energy Constructs"},
          {"url": "https://www.superherodb.com/energy-embodiment/60-329/*/", "name": "Energy Embodiment"},
          {"url": "https://www.superherodb.com/energy-manipulation/60-123/*/", "name": "Energy Manipulation"},
          {"url": "https://www.superherodb.com/energy-resistance/60-136/*/", "name": "Energy Resistance"},
          {"url": "https://www.superherodb.com/enhanced-condition/60-475/*/", "name": "Enhanced Condition"},
          {"url": "https://www.superherodb.com/enhanced-hearing/60-100/*/", "name": "Enhanced Hearing"},
          {"url": "https://www.superherodb.com/enhanced-memory/60-156/*/", "name": "Enhanced Memory"},
          {"url": "https://www.superherodb.com/enhanced-smell/60-160/*/", "name": "Enhanced Smell"},
          {"url": "https://www.superherodb.com/enhanced-taste/60-537/*/", "name": "Enhanced Taste"},
          {"url": "https://www.superherodb.com/enhanced-thievery/60-378/*/", "name": "Enhanced Thievery"},
          {"url": "https://www.superherodb.com/enhanced-touch/60-173/*/", "name": "Enhanced Touch"},
          {"url": "https://www.superherodb.com/enigma-force/60-429/*/", "name": "Enigma Force"},
          {"url": "https://www.superherodb.com/entropy-projection/60-31/*/", "name": "Entropy Projection"},
          {
            "url": "https://www.superherodb.com/existence-erasure-resistance/60-336/*/",
            "name": "Existence Erasure Resistance",
          },
          {"url": "https://www.superherodb.com/existence-erasure/60-233/*/", "name": "Existence Erasure"},
          {"url": "https://www.superherodb.com/exorcism/60-352/*/", "name": "Exorcism"},
          {"url": "https://www.superherodb.com/explosion-manipulation/60-208/*/", "name": "Explosion Manipulation"},
          {"url": "https://www.superherodb.com/extrasensory-perception/60-316/*/", "name": "Extrasensory Perception"},
          {"url": "https://www.superherodb.com/fate-manipulation/60-220/*/", "name": "Fate Manipulation"},
          {"url": "https://www.superherodb.com/fate-resistance/60-375/*/", "name": "Fate Resistance"},
          {"url": "https://www.superherodb.com/fear-inducement/60-312/*/", "name": "Fear Inducement"},
          {"url": "https://www.superherodb.com/fear-manipulation/60-206/*/", "name": "Fear Manipulation"},
          {"url": "https://www.superherodb.com/fire-control/60-23/*/", "name": "Fire Control"},
          {"url": "https://www.superherodb.com/fire-resistance/60-139/*/", "name": "Fire Resistance"},
          {"url": "https://www.superherodb.com/flight/60-88/*/", "name": "Flight"},
          {"url": "https://www.superherodb.com/food-manipulation/60-330/*/", "name": "Food Manipulation"},
          {"url": "https://www.superherodb.com/force-fields/60-32/*/", "name": "Force Fields"},
          {"url": "https://www.superherodb.com/force-ghost/60-294/*/", "name": "Force Ghost"},
          {"url": "https://www.superherodb.com/fusion/60-245/*/", "name": "Fusion"},
          {"url": "https://www.superherodb.com/gadget-usage/60-514/*/", "name": "Gadget Usage"},
          {"url": "https://www.superherodb.com/gliding/60-89/*/", "name": "Gliding"},
          {"url": "https://www.superherodb.com/goblin-force/60-535/*/", "name": "Goblin Force"},
          {"url": "https://www.superherodb.com/grapplingclimbing/60-483/*/", "name": "Grappling/Climbing"},
          {"url": "https://www.superherodb.com/gravity-control/60-17/*/", "name": "Gravity Control"},
          {"url": "https://www.superherodb.com/greed-inducement/60-313/*/", "name": "Greed Inducement"},
          {"url": "https://www.superherodb.com/hacking/60-227/*/", "name": "Hacking"},
          {"url": "https://www.superherodb.com/hair-manipulation/60-185/*/", "name": "Hair Manipulation"},
          {"url": "https://www.superherodb.com/heat-generation/60-177/*/", "name": "Heat Generation"},
          {"url": "https://www.superherodb.com/heat-resistance/60-142/*/", "name": "Heat Resistance"},
          {"url": "https://www.superherodb.com/hellfire-manipulation/60-286/*/", "name": "Hellfire Manipulation"},
          {"url": "https://www.superherodb.com/hellfire-resistance/60-366/*/", "name": "Hellfire Resistance"},
          {
            "url": "https://www.superherodb.com/higher-dimensional-manipulation/60-215/*/",
            "name": "Higher Dimensional Manipulation",
          },
          {"url": "https://www.superherodb.com/hive-mind/60-496/*/", "name": "Hive-Mind"},
          {"url": "https://www.superherodb.com/holy-manipulation/60-246/*/", "name": "Holy Manipulation"},
          {"url": "https://www.superherodb.com/holy-resistance/60-370/*/", "name": "Holy Resistance"},
          {"url": "https://www.superherodb.com/homing-attack/60-271/*/", "name": "Homing Attack"},
          {"url": "https://www.superherodb.com/hope-inducement/60-310/*/", "name": "Hope Inducement"},
          {"url": "https://www.superherodb.com/hunters-instinct/60-479/*/", "name": "Hunters Instinct"},
          {"url": "https://www.superherodb.com/hyperkinesis/60-178/*/", "name": "Hyperkinesis"},
          {"url": "https://www.superherodb.com/hypnokinesis/60-19/*/", "name": "Hypnokinesis"},
          {"url": "https://www.superherodb.com/hypnotic-suggestion/60-495/*/", "name": "Hypnotic Suggestion"},
          {"url": "https://www.superherodb.com/illumination/60-145/*/", "name": "Illumination"},
          {"url": "https://www.superherodb.com/illusion-resistance/60-492/*/", "name": "Illusion Resistance"},
          {"url": "https://www.superherodb.com/illusions/60-44/*/", "name": "Illusions"},
          {"url": "https://www.superherodb.com/immortality-negation/60-459/*/", "name": "Immortality Negation"},
          {"url": "https://www.superherodb.com/immortality/60-75/*/", "name": "Immortality"},
          {
            "url": "https://www.superherodb.com/indestructible-digestion/60-272/*/",
            "name": "Indestructible Digestion",
          },
          {"url": "https://www.superherodb.com/indomitable-will/60-295/*/", "name": "Indomitable Will"},
          {"url": "https://www.superherodb.com/information-analysis/60-234/*/", "name": "Information Analysis"},
          {
            "url": "https://www.superherodb.com/information-manipulation/60-365/*/",
            "name": "Information Manipulation",
          },
          {"url": "https://www.superherodb.com/insanity/60-58/*/", "name": "Insanity"},
          {"url": "https://www.superherodb.com/instinctive-reaction/60-235/*/", "name": "Instinctive Reaction"},
          {"url": "https://www.superherodb.com/intangibility/60-113/*/", "name": "Intangibility"},
          {"url": "https://www.superherodb.com/intelligence/60-59/*/", "name": "Intelligence"},
          {"url": "https://www.superherodb.com/intuitive-aptitude/60-154/*/", "name": "Intuitive aptitude"},
          {"url": "https://www.superherodb.com/invisibility/60-4/*/", "name": "Invisibility"},
          {"url": "https://www.superherodb.com/invulnerability/60-76/*/", "name": "Invulnerability"},
          {"url": "https://www.superherodb.com/jaw-strength/60-467/*/", "name": "Jaw Strength"},
          {"url": "https://www.superherodb.com/jump/60-93/*/", "name": "Jump"},
          {"url": "https://www.superherodb.com/lantern-power-ring/60-137/*/", "name": "Lantern Power Ring"},
          {"url": "https://www.superherodb.com/large-size/60-478/*/", "name": "Large Size"},
          {"url": "https://www.superherodb.com/laser-manipulation/60-485/*/", "name": "Laser Manipulation"},
          {"url": "https://www.superherodb.com/latent-abilities/60-45/*/", "name": "Latent Abilities"},
          {"url": "https://www.superherodb.com/law-manipulation/60-247/*/", "name": "Law Manipulation"},
          {"url": "https://www.superherodb.com/levitation/60-90/*/", "name": "Levitation"},
          {"url": "https://www.superherodb.com/life-manipulation/60-222/*/", "name": "Life Manipulation"},
          {"url": "https://www.superherodb.com/light-control/60-21/*/", "name": "Light Control"},
          {"url": "https://www.superherodb.com/liquid-transmutation/60-340/*/", "name": "Liquid Transmutation"},
          {"url": "https://www.superherodb.com/longevity/60-141/*/", "name": "Longevity"},
          {"url": "https://www.superherodb.com/love-inducement/60-309/*/", "name": "Love Inducement"},
          {"url": "https://www.superherodb.com/luck/60-373/*/", "name": "Luck"},
          {"url": "https://www.superherodb.com/madness-manipulation/60-324/*/", "name": "Madness Manipulation"},
          {"url": "https://www.superherodb.com/magic-absorption/60-489/*/", "name": "Magic Absorption"},
          {"url": "https://www.superherodb.com/magic-resistance/60-133/*/", "name": "Magic Resistance"},
          {"url": "https://www.superherodb.com/magic/60-46/*/", "name": "Magic"},
          {"url": "https://www.superherodb.com/magma-manipulation/60-364/*/", "name": "Magma Manipulation"},
          {"url": "https://www.superherodb.com/magnetism/60-20/*/", "name": "Magnetism"},
          {"url": "https://www.superherodb.com/marksmanship/60-84/*/", "name": "Marksmanship"},
          {"url": "https://www.superherodb.com/master-martial-artist/60-268/*/", "name": "Master Martial Artist"},
          {"url": "https://www.superherodb.com/master-tactician/60-284/*/", "name": "Master Tactician"},
          {"url": "https://www.superherodb.com/matter-absorption/60-166/*/", "name": "Matter Absorption"},
          {"url": "https://www.superherodb.com/matter-manipulation/60-194/*/", "name": "Matter Manipulation"},
          {"url": "https://www.superherodb.com/mechanical-aptitude/60-280/*/", "name": "Mechanical Aptitude"},
          {"url": "https://www.superherodb.com/melting/60-155/*/", "name": "Melting"},
          {"url": "https://www.superherodb.com/memory-manipulation/60-209/*/", "name": "Memory Manipulation"},
          {"url": "https://www.superherodb.com/metal-manipulation/60-248/*/", "name": "Metal Manipulation"},
          {
            "url": "https://www.superherodb.com/metaphysics-manipulation/60-463/*/",
            "name": "Metaphysics Manipulation",
          },
          {"url": "https://www.superherodb.com/mind-blast/60-47/*/", "name": "Mind Blast"},
          {"url": "https://www.superherodb.com/mind-control-resistance/60-116/*/", "name": "Mind Control Resistance"},
          {"url": "https://www.superherodb.com/mind-control/60-48/*/", "name": "Mind Control"},
          {"url": "https://www.superherodb.com/mind-transfer/60-408/*/", "name": "Mind Transfer"},
          {"url": "https://www.superherodb.com/molecular-combustion/60-77/*/", "name": "Molecular Combustion"},
          {"url": "https://www.superherodb.com/molecular-dissipation/60-79/*/", "name": "Molecular Dissipation"},
          {"url": "https://www.superherodb.com/molecular-immobilization/60-78/*/", "name": "Molecular Immobilization"},
          {"url": "https://www.superherodb.com/molecular-manipulation/60-126/*/", "name": "Molecular Manipulation"},
          {"url": "https://www.superherodb.com/morality-manipulation/60-349/*/", "name": "Morality Manipulation"},
          {"url": "https://www.superherodb.com/multiple-limbs/60-471/*/", "name": "Multiple Limbs"},
          {"url": "https://www.superherodb.com/multiple-personalities/60-351/*/", "name": "Multiple Personalities"},
          {"url": "https://www.superherodb.com/nanotechnology/60-323/*/", "name": "Nanotechnology"},
          {"url": "https://www.superherodb.com/natural-armor/60-80/*/", "name": "Natural Armor"},
          {"url": "https://www.superherodb.com/natural-weapons/60-81/*/", "name": "Natural Weapons"},
          {"url": "https://www.superherodb.com/necromancy/60-221/*/", "name": "Necromancy"},
          {"url": "https://www.superherodb.com/negative-speed-force/60-500/*/", "name": "Negative Speed Force"},
          {"url": "https://www.superherodb.com/nen-manipulation/60-379/*/", "name": "Nen Manipulation"},
          {"url": "https://www.superherodb.com/neon-blasts/60-264/*/", "name": "Neon Blasts"},
          {"url": "https://www.superherodb.com/new-power/60-415/*/", "name": "New Power"},
          {"url": "https://www.superherodb.com/nigh-omnipotence/60-195/*/", "name": "Nigh-Omnipotence"},
          {"url": "https://www.superherodb.com/nigh-omnipresence/60-196/*/", "name": "Nigh-Omnipresence"},
          {"url": "https://www.superherodb.com/nigh-omniscience/60-197/*/", "name": "Nigh-Omniscience"},
          {"url": "https://www.superherodb.com/ninjutsu/60-292/*/", "name": "Ninjutsu"},
          {"url": "https://www.superherodb.com/non-corporeal/60-236/*/", "name": "Non-Corporeal"},
          {
            "url": "https://www.superherodb.com/non-physical-interaction/60-224/*/",
            "name": "Non-Physical Interaction",
          },
          {"url": "https://www.superherodb.com/nonexistent-physiology/60-532/*/", "name": "Nonexistent Physiology"},
          {
            "url": "https://www.superherodb.com/nothingness-aspect-manifestation/60-298/*/",
            "name": "Nothingness Aspect Manifestation",
          },
          {"url": "https://www.superherodb.com/nova-force/60-163/*/", "name": "Nova Force"},
          {"url": "https://www.superherodb.com/ocular-techniques/60-337/*/", "name": "Ocular Techniques"},
          {"url": "https://www.superherodb.com/odin-force/60-186/*/", "name": "Odin Force"},
          {"url": "https://www.superherodb.com/old-power/60-414/*/", "name": "Old Power"},
          {"url": "https://www.superherodb.com/omega-effect/60-191/*/", "name": "Omega Effect"},
          {"url": "https://www.superherodb.com/omega-sanction/60-398/*/", "name": "Omega Sanction"},
          {"url": "https://www.superherodb.com/omni-sense/60-250/*/", "name": "Omni-Sense"},
          {"url": "https://www.superherodb.com/omnifabrication/60-249/*/", "name": "Omnifabrication"},
          {"url": "https://www.superherodb.com/omnilingualism/60-49/*/", "name": "Omnilingualism"},
          {"url": "https://www.superherodb.com/omnilock/60-281/*/", "name": "Omnilock"},
          {"url": "https://www.superherodb.com/omnimimicry/60-482/*/", "name": "Omnimimicry"},
          {"url": "https://www.superherodb.com/omnipotence/60-127/*/", "name": "Omnipotence"},
          {"url": "https://www.superherodb.com/omnipresence/60-189/", "name": "Omnipresence"},
          {"url": "https://www.superherodb.com/omniscience/60-188/", "name": "Omniscience"},
          {"url": "https://www.superherodb.com/omnitrix/60-165/", "name": "Omnitrix"},
          {"url": "https://www.superherodb.com/organic-manipulation/60-342/", "name": "Organic Manipulation"},
          {"url": "https://www.superherodb.com/origin-manipulation/60-464/", "name": "Origin Manipulation"},
          {"url": "https://www.superherodb.com/pacemiakinesis/60-525/", "name": "Pacemiakinesis"},
          {"url": "https://www.superherodb.com/pain-manipulation/60-207/", "name": "Pain Manipulation"},
          {"url": "https://www.superherodb.com/pain-suppression/60-383/", "name": "Pain Suppression"},
          {"url": "https://www.superherodb.com/paper-manipulation/60-367/", "name": "Paper Manipulation"},
          {"url": "https://www.superherodb.com/paradox-manipulation/60-533/", "name": "Paradox Manipulation"},
          {"url": "https://www.superherodb.com/paralysis/60-265/", "name": "Paralysis"},
          {"url": "https://www.superherodb.com/pataphysics-manipulation/60-462/", "name": "Pataphysics Manipulation"},
          {"url": "https://www.superherodb.com/peak-human-condition/60-140/", "name": "Peak Human Condition"},
          {"url": "https://www.superherodb.com/penance-stare/60-502/", "name": "Penance Stare"},
          {"url": "https://www.superherodb.com/perfect-recollection/60-253/", "name": "Perfect Recollection"},
          {"url": "https://www.superherodb.com/perspective-manipulation/60-534/", "name": "Perspective Manipulation"},
          {"url": "https://www.superherodb.com/petrification/60-347/", "name": "Petrification"},
          {"url": "https://www.superherodb.com/phasing/60-114/", "name": "Phasing"},
          {"url": "https://www.superherodb.com/phoenix-force/60-187/", "name": "Phoenix Force"},
          {"url": "https://www.superherodb.com/photographic-deduction/60-516/", "name": "Photographic Deduction"},
          {"url": "https://www.superherodb.com/photographic-reflexes/60-82/", "name": "Photographic Reflexes"},
          {"url": "https://www.superherodb.com/physical-anomaly/60-5/", "name": "Physical Anomaly"},
          {"url": "https://www.superherodb.com/physics-manipulation/60-225/", "name": "Physics Manipulation"},
          {"url": "https://www.superherodb.com/plant-control/60-12/", "name": "Plant Control"},
          {"url": "https://www.superherodb.com/plasma-manipulation/60-346/", "name": "Plasma Manipulation"},
          {
            "url": "https://www.superherodb.com/plot-manipulation-resistance/60-407/",
            "name": "Plot Manipulation Resistance",
          },
          {"url": "https://www.superherodb.com/plot-manipulation/60-237/", "name": "Plot Manipulation"},
          {"url": "https://www.superherodb.com/pocket-dimensions/60-307/", "name": "Pocket Dimensions"},
          {"url": "https://www.superherodb.com/portal-creation/60-92/", "name": "Portal Creation"},
          {"url": "https://www.superherodb.com/possession-resistance/60-334/", "name": "Possession Resistance"},
          {"url": "https://www.superherodb.com/possession/60-50/", "name": "Possession"},
          {"url": "https://www.superherodb.com/postcognition/60-411/", "name": "Postcognition"},
          {
            "url": "https://www.superherodb.com/power-absorption-immunity/60-353/",
            "name": "Power Absorption Immunity",
          },
          {"url": "https://www.superherodb.com/power-absorption/60-33/", "name": "Power Absorption"},
          {"url": "https://www.superherodb.com/power-augmentation/60-132/", "name": "Power Augmentation"},
          {"url": "https://www.superherodb.com/power-bestowal/60-210/", "name": "Power Bestowal"},
          {"url": "https://www.superherodb.com/power-cosmic/60-128/", "name": "Power Cosmic"},
          {"url": "https://www.superherodb.com/power-mimicry-immunity/60-354/", "name": "Power Mimicry Immunity"},
          {"url": "https://www.superherodb.com/power-mimicry/60-239/", "name": "Power Mimicry"},
          {"url": "https://www.superherodb.com/power-modification/60-301/", "name": "Power Modification"},
          {"url": "https://www.superherodb.com/power-nullifier/60-129/", "name": "Power Nullifier"},
          {"url": "https://www.superherodb.com/power-primordial/60-395/", "name": "Power Primordial"},
          {"url": "https://www.superherodb.com/power-sense/60-158/", "name": "Power Sense"},
          {"url": "https://www.superherodb.com/power-suit/60-159/", "name": "Power Suit"},
          {"url": "https://www.superherodb.com/precognition/60-51/", "name": "Precognition"},
          {"url": "https://www.superherodb.com/preparation/60-369/", "name": "Preparation"},
          {"url": "https://www.superherodb.com/pressure-points/60-274/", "name": "Pressure Points"},
          {"url": "https://www.superherodb.com/probability-manipulation/60-52/", "name": "Probability Manipulation"},
          {"url": "https://www.superherodb.com/projection/60-53/", "name": "Projection"},
          {"url": "https://www.superherodb.com/psychometry/60-287/", "name": "Psychometry"},
          {"url": "https://www.superherodb.com/purification/60-320/", "name": "Purification"},
          {"url": "https://www.superherodb.com/radar-sense/60-174/", "name": "Radar Sense"},
          {"url": "https://www.superherodb.com/radiation-absorption/60-115/", "name": "Radiation Absorption"},
          {"url": "https://www.superherodb.com/radiation-control/60-54/", "name": "Radiation Control"},
          {"url": "https://www.superherodb.com/radiation-immunity/60-143/", "name": "Radiation Immunity"},
          {"url": "https://www.superherodb.com/rage-inducement/60-308/", "name": "Rage Inducement"},
          {"url": "https://www.superherodb.com/rage-power/60-269/", "name": "Rage Power"},
          {"url": "https://www.superherodb.com/rainbow-energy/60-469/", "name": "Rainbow Energy"},
          {"url": "https://www.superherodb.com/reactive-evolution/60-231/", "name": "Reactive Evolution"},
          {
            "url": "https://www.superherodb.com/reality-warping-resistance/60-412/",
            "name": "Reality Warping Resistance",
          },
          {"url": "https://www.superherodb.com/reality-warping/60-55/", "name": "Reality Warping"},
          {"url": "https://www.superherodb.com/reflexes/60-108/", "name": "Reflexes"},
          {"url": "https://www.superherodb.com/regeneration-negation/60-460/", "name": "Regeneration Negation"},
          {"url": "https://www.superherodb.com/regeneration/60-144/", "name": "Regeneration"},
          {"url": "https://www.superherodb.com/resurrection/60-135/", "name": "Resurrection"},
          {"url": "https://www.superherodb.com/robotic-engineering/60-275/", "name": "Robotic Engineering"},
          {"url": "https://www.superherodb.com/rune-magic/60-254/", "name": "Rune Magic"},
          {"url": "https://www.superherodb.com/salvation/60-283/", "name": "Salvation"},
          {"url": "https://www.superherodb.com/sand-manipulation/60-472/", "name": "Sand Manipulation"},
          {"url": "https://www.superherodb.com/scanning/60-523/", "name": "Scanning"},
          {"url": "https://www.superherodb.com/sealing/60-255/", "name": "Sealing"},
          {"url": "https://www.superherodb.com/seismic-power/60-147/", "name": "Seismic Power"},
          {"url": "https://www.superherodb.com/self-destruction/60-229/", "name": "Self-Destruction"},
          {"url": "https://www.superherodb.com/self-sustenance/60-138/", "name": "Self-Sustenance"},
          {"url": "https://www.superherodb.com/sense-manipulation/60-350/", "name": "Sense Manipulation"},
          {"url": "https://www.superherodb.com/separation/60-83/", "name": "Separation"},
          {"url": "https://www.superherodb.com/shapeshifting/60-6/", "name": "Shapeshifting"},
          {"url": "https://www.superherodb.com/shockwaves-generation/60-427/", "name": "Shockwaves Generation"},
          {"url": "https://www.superherodb.com/size-changing/60-7/", "name": "Size Changing"},
          {"url": "https://www.superherodb.com/sleep-manipulation/60-211/", "name": "Sleep Manipulation"},
          {"url": "https://www.superherodb.com/smoke-manipulation/60-212/", "name": "Smoke Manipulation"},
          {"url": "https://www.superherodb.com/social-influencing/60-368/", "name": "Social Influencing"},
          {"url": "https://www.superherodb.com/sonic-scream/60-34/", "name": "Sonic Scream"},
          {"url": "https://www.superherodb.com/sotobro-effect/60-474/", "name": "Sotobro Effect"},
          {"url": "https://www.superherodb.com/soul-manipulation/60-226/", "name": "Soul Manipulation"},
          {"url": "https://www.superherodb.com/soul-resistance/60-376/", "name": "Soul Resistance"},
          {"url": "https://www.superherodb.com/space-survivability/60-515/", "name": "Space Survivability"},
          {"url": "https://www.superherodb.com/spaceflight/60-348/", "name": "Spaceflight"},
          {"url": "https://www.superherodb.com/spatial-awareness/60-179/", "name": "Spatial Awareness"},
          {"url": "https://www.superherodb.com/spatial-communication/60-413/", "name": "Spatial Communication"},
          {"url": "https://www.superherodb.com/spatial-manipulation/60-256/", "name": "Spatial Manipulation"},
          {"url": "https://www.superherodb.com/speed-force/60-190/", "name": "Speed Force"},
          {"url": "https://www.superherodb.com/spinjitzu/60-240/", "name": "Spinjitzu"},
          {"url": "https://www.superherodb.com/spirit-control/60-498/", "name": "Spirit Control"},
          {"url": "https://www.superherodb.com/stamina/60-106/", "name": "Stamina"},
          {"url": "https://www.superherodb.com/stands/60-263/", "name": "Stands"},
          {"url": "https://www.superherodb.com/stasis/60-518/", "name": "Stasis"},
          {"url": "https://www.superherodb.com/statistics-amplification/60-213/", "name": "Statistics Amplification"},
          {"url": "https://www.superherodb.com/statistics-reduction/60-321/", "name": "Statistics Reduction"},
          {"url": "https://www.superherodb.com/status-effect-inducement/60-257/", "name": "Status Effect Inducement"},
          {"url": "https://www.superherodb.com/stealth/60-176/", "name": "Stealth"},
          {"url": "https://www.superherodb.com/strength-force/60-494/", "name": "Strength Force"},
          {"url": "https://www.superherodb.com/sub-mariner/60-171/", "name": "Sub-Mariner"},
          {"url": "https://www.superherodb.com/subatomic-manipulation/60-468/", "name": "Subatomic Manipulation"},
          {"url": "https://www.superherodb.com/subjective-reality/60-302/", "name": "Subjective Reality"},
          {"url": "https://www.superherodb.com/substance-secretion/60-153/", "name": "Substance Secretion"},
          {"url": "https://www.superherodb.com/subterranean/60-484/", "name": "Subterranean"},
          {"url": "https://www.superherodb.com/summoning/60-56/", "name": "Summoning"},
          {"url": "https://www.superherodb.com/super-breath/60-101/", "name": "Super Breath"},
          {"url": "https://www.superherodb.com/super-speed/60-94/", "name": "Super Speed"},
          {"url": "https://www.superherodb.com/super-strength/60-85/", "name": "Super Strength"},
          {"url": "https://www.superherodb.com/supernatural-condition/60-422/", "name": "Supernatural Condition"},
          {"url": "https://www.superherodb.com/supreme-power/60-461/", "name": "Supreme Power"},
          {"url": "https://www.superherodb.com/surface-scaling/60-402/", "name": "Surface Scaling"},
          {"url": "https://www.superherodb.com/swordsmanship/60-466/", "name": "Swordsmanship"},
          {"url": "https://www.superherodb.com/symbiote-costume/60-118/", "name": "Symbiote Costume"},
          {"url": "https://www.superherodb.com/symbiotic-regeneration/60-338/", "name": "Symbiotic Regeneration"},
          {"url": "https://www.superherodb.com/technological-possession/60-374/", "name": "Technological Possession"},
          {"url": "https://www.superherodb.com/technopathcyberpath/60-61/", "name": "Technopath/Cyberpath"},
          {"url": "https://www.superherodb.com/telekinesis/60-99/", "name": "Telekinesis"},
          {"url": "https://www.superherodb.com/telepathy-resistance/60-130/", "name": "Telepathy Resistance"},
          {"url": "https://www.superherodb.com/telepathy/60-62/", "name": "Telepathy"},
          {"url": "https://www.superherodb.com/teleportation/60-95/", "name": "Teleportation"},
          {"url": "https://www.superherodb.com/tentacles/60-470/", "name": "Tentacles"},
          {"url": "https://www.superherodb.com/terrakinesis/60-24/", "name": "Terrakinesis"},
          {"url": "https://www.superherodb.com/the-clear/60-506/", "name": "The Clear"},
          {"url": "https://www.superherodb.com/the-divided/60-511/", "name": "The Divided"},
          {"url": "https://www.superherodb.com/the-force/60-183/", "name": "The Force"},
          {"url": "https://www.superherodb.com/the-fourth-wall/60-262/", "name": "The Fourth Wall"},
          {"url": "https://www.superherodb.com/the-green/60-192/", "name": "The Green"},
          {"url": "https://www.superherodb.com/the-grey/60-510/", "name": "The Grey"},
          {"url": "https://www.superherodb.com/the-metal/60-508/", "name": "The Metal"},
          {"url": "https://www.superherodb.com/the-red/60-505/", "name": "The Red"},
          {"url": "https://www.superherodb.com/the-white/60-504/", "name": "The White"},
          {"url": "https://www.superherodb.com/thirstokinesis/60-164/", "name": "Thirstokinesis"},
          {"url": "https://www.superherodb.com/thread-manipulation/60-538/", "name": "Thread Manipulation"},
          {
            "url": "https://www.superherodb.com/time-manipulation-resistance/60-396/",
            "name": "Time Manipulation Resistance",
          },
          {"url": "https://www.superherodb.com/time-manipulation/60-13/", "name": "Time Manipulation"},
          {"url": "https://www.superherodb.com/time-travel/60-97/", "name": "Time Travel"},
          {"url": "https://www.superherodb.com/toon-force/60-241/", "name": "Toon Force"},
          {
            "url": "https://www.superherodb.com/toxin-and-disease-control/60-134/",
            "name": "Toxin and Disease Control",
          },
          {
            "url": "https://www.superherodb.com/toxin-and-disease-resistance/60-131/",
            "name": "Toxin and Disease Resistance",
          },
          {"url": "https://www.superherodb.com/transformation/60-258/", "name": "Transformation"},
          {"url": "https://www.superherodb.com/transmutation-immunity/60-527/", "name": "Transmutation Immunity"},
          {"url": "https://www.superherodb.com/umbrakinesis/60-26/", "name": "Umbrakinesis"},
          {"url": "https://www.superherodb.com/underwater-breathing/60-146/", "name": "Underwater breathing"},
          {"url": "https://www.superherodb.com/unholy-manipulation/60-304/", "name": "Unholy Manipulation"},
          {"url": "https://www.superherodb.com/unholy-resistance/60-371/", "name": "Unholy Resistance"},
          {"url": "https://www.superherodb.com/uni-power/60-198/", "name": "Uni-Power"},
          {"url": "https://www.superherodb.com/vaporising-beams/60-35/", "name": "Vaporising Beams"},
          {"url": "https://www.superherodb.com/vehicular-mastery/60-322/", "name": "Vehicular Mastery"},
          {"url": "https://www.superherodb.com/venomous-bite/60-387/", "name": "Venomous Bite"},
          {"url": "https://www.superherodb.com/vibration-manipulation/60-259/", "name": "Vibration Manipulation"},
          {"url": "https://www.superherodb.com/vision-cryo/60-180/", "name": "Vision - Cryo"},
          {"url": "https://www.superherodb.com/vision-heat/60-103/", "name": "Vision - Heat"},
          {"url": "https://www.superherodb.com/vision-infrared/60-175/", "name": "Vision - Infrared"},
          {"url": "https://www.superherodb.com/vision-microscopic/60-105/", "name": "Vision -Microscopic"},
          {"url": "https://www.superherodb.com/vision-night/60-119/", "name": "Vision - Night"},
          {"url": "https://www.superherodb.com/vision-telescopic/60-104/", "name": "Vision - Telescopic"},
          {"url": "https://www.superherodb.com/vision-thermal/60-121/", "name": "Vision - Thermal"},
          {"url": "https://www.superherodb.com/vision-x-ray/60-102/", "name": "Vision - X - Ray"},
          {"url": "https://www.superherodb.com/vitakinesis/60-27/", "name": "Vitakinesis"},
          {"url": "https://www.superherodb.com/void-manipulation/60-260/", "name": "Void Manipulation"},
          {"url": "https://www.superherodb.com/vortex-creation/60-405/", "name": "Vortex Creation"},
          {"url": "https://www.superherodb.com/water-control/60-18/", "name": "Water Control"},
          {"url": "https://www.superherodb.com/weapon-based-powers/60-86/", "name": "Weapon -based Powers"},
          {"url": "https://www.superherodb.com/weapon-creation/60-214/", "name": "Weapon Creation"},
          {"url": "https://www.superherodb.com/weapon-summoning/60-499/", "name": "Weapon Summoning"},
          {"url": "https://www.superherodb.com/weapons-master/60-167/", "name": "Weapons Master"},
          {"url": "https://www.superherodb.com/weather-control/60-9/", "name": "Weather Control"},
          {"url": "https://www.superherodb.com/web-creation/60-170/", "name": "Web Creation"},
          {"url": "https://www.superherodb.com/willpower-inducement/60-314/", "name": "Willpower Inducement"},
          {"url": "https://www.superherodb.com/willpower-manipulation/60-261/", "name": "Willpower Manipulation"},
          {"url": "https://www.superherodb.com/wind-control/60-8/", "name": "Wind Control"},
          {"url": "https://www.superherodb.com/wing-manifestation/60-503/", "name": "Wing Manifestation"},
          {"url": "https://www.superherodb.com/wishing/60-60/", "name": "Wishing"},
          {"url": "https://www.superherodb.com/wood-manipulation/60-473/", "name": "Wood Manipulation"},
          {"url": "https://www.superherodb.com/writing-manipulation/60-339/", "name": "Writing Manipulation"},
          {"url": "https://www.superherodb.com/zenith/60-288/", "name": "Zenith"},
        ]
      }
    }
  }

}
</script>
